Update conditional_stuff.yml

diff --git a/.github/workflows/conditional_stuff.yml b/.github/workflows/conditional_stuff.yml
--- a/.github/workflows/conditional_stuff.yml
+++ b/.github/workflows/conditional_stuff.yml
@@ -19,3 +19,22 @@ jobs:
       - name: no was passed in as "fail_my_step"
         run: echo "you said no!! :("
         if: inputs.fail_my_step == 'no'
+
+      - name: Step that may fail
+        shell: bash
+        run: |
+          echo "Hello, I may fail"
+          if [ "yes" = "${{ inputs.fail_my_step }}" ]; then
+            exit 42
+          fi
+
+      - name: Another step
+        run: echo "another step..."
+
+      - name: Another step
+        run: echo "another step..."
+          
+
+
+
+        
