Update Övning1.yml

diff --git a/.github/workflows/Övning1.yml b/.github/workflows/Övning1.yml
--- a/.github/workflows/Övning1.yml
+++ b/.github/workflows/Övning1.yml
@@ -14,10 +14,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: a number over 7 was passed in "succeed_if_number_over_7"
-        if: inputs.succeed_if_number_over_7 > '7'
+        if: inputs.succeed_if_number_over_7 > '7' 
         run: echo "you are above 7!! :)"
 
-      - name: a number under 7 was passed in "succeed_if_number_over_7"
-        if: inputs.succeed_if_number_over_7 < '7'
-        run: echo "you are under 7!! :("
+      - name: Step that fail under 7
+        shell: bash
+        run: |
+          echo "Hello, I may fail"
+          if [ ${{ 'inputs.succeed_if_number_over_7' }} -lt '7' ]; then
+            exit 42
+          fi
+      
     
